name: Update israeli-bank-scrapers

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'information'
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
      tags:
        description: 'Purpose of Run This Workflow?'
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Check for updates in israeli-bank-scrapers
        run: yarn outdated israeli-bank-scrapers --json

      - name: Upgrade israeli-bank-scrapers
        run: yarn upgrade israeli-bank-scrapers

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: Upgrade israeli-bank-scrapers library" || echo "No changes to commit"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Upgrade israeli-bank-scrapers library'
          title: 'Upgrade israeli-bank-scrapers library'
          body: |
            Changes:
            - [Diff Link](link_to_diff)
            - Description of versions difference
